---
abstract: 'A simple HTTP client based on POE::Declare'
author:
  - 'Adam Kennedy <adamk@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  File::Remove: 1.42
  Test::More: 0.47
  Test::POE::Stopping: 1.00
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: POE::Declare::Log::File
name: POE-Declare-Log-File
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  File::Spec: 0.80
  POE: 1.293
  POE::Declare: 0.54
  perl: 5.8.0
resources:
  ChangeLog: http://fisheye2.atlassian.com/changelog/cpan/trunk/POE-Declare-Log-File
  license: http://dev.perl.org/licenses/
  repository: http://svn.ali.as/cpan/trunk/POE-Declare-Log-File
version: 0.01
